---
title: "Mapping the risk environment with oepsData"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(oepsData)
```

```{r documentation}
# 
# ?load_oeps_dictionary
# ?load_oeps
```

```{r preview data}
# See what data is available
data_dictionary <- load_oeps_dictionary(scale='tract')
data_dictionary
```

```{r}
# Grab the data
cook_county_2010 <- load_oeps(
  scale='tract', 
  year='2010', 
  themes=c('social', 'economic'), 
  states='17', 
  counties='031',
  geometry=T)

# Preview what we got
head(data.frame(cook_county_2010))
```

```{r}
library(tmap)
tm_shape(cook_county_2010) + 
  tm_fill(c('Age18_64', 'PovP'), 
          title = c('Working Age', 'Poverty\nPercentage'),
          style = c('sd', 'sd'),
          palette = 'BrBG') + 
  tm_layout(legend.position = c('left', 'bottom'), frame=FALSE, main.title = 'Fewer workers correlates with higher poverty in Cook')
```

```{r}
# Grab the data
chicago_metro_2010 <- load_oeps(
  scale='tract', 
  year='2010', 
  theme=c('social', 'economic'), 
  counties=c('17031', '18089'),
  geometry=T)

# Preview what we got
head(data.frame(cook_county_2010))
```

```{r}
library(tmap)
tm_shape(chicago_metro_2010) + 
  tm_fill(c('Age18_64', 'PovP'), 
          title = c('Working Age', 'Poverty\nPercentage'),
          style = c('sd', 'sd'),
          palette = 'BrBG') + 
  tm_layout(legend.position = c('left', 'bottom'), frame=FALSE, main.title = 'Fewer workers correlates with higher poverty near Chi')
```